import "./globals.css";


export const metadata = {
  title: "MyMyWorld",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        {children}
        <script src="//code.tidio.co/qgbzbvjj97nukk4u7mvxcblkl6kxdr76.js" async></script>
      </body>
    </html>
  );
}
